# Generated by Django 2.1.1 on 2018-10-08 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Painter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slug', models.CharField(max_length=250, unique=True)),
                ('birth', models.DateField()),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'painter',
                'verbose_name_plural': 'painters',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Painting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('description', models.TextField(blank=True)),
                ('width', models.IntegerField(default=10)),
                ('height', models.IntegerField(default=10)),
                ('price', models.IntegerField(default=100000)),
                ('image', models.ImageField(upload_to='painting')),
                ('available', models.BooleanField(default=True)),
                ('painter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Painter')),
            ],
            options={
                'verbose_name': 'painting',
                'verbose_name_plural': 'paintings',
                'ordering': ('name',),
            },
        ),
    ]
