# Generated by Django 2.1.1 on 2018-10-15 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='painter',
            name='image',
            field=models.ImageField(blank=True, upload_to='user_profile'),
        ),
    ]
