# Generated by Django 2.1.1 on 2018-10-17 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_painting_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='painter',
            name='title',
            field=models.CharField(default='', max_length=35),
        ),
    ]
