# Generated by Django 2.1.1 on 2018-11-02 07:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_painter_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='painting',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
