# Generated by Django 2.1.1 on 2018-11-04 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20181104_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='paintingimg',
            name='image',
            field=models.ImageField(default='', upload_to='paintingImgs'),
        ),
    ]
