# Generated by Django 2.1.1 on 2018-11-06 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20181106_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painter',
            name='image',
            field=models.ImageField(default='img/profile_default.jpg', upload_to='user_profile'),
        ),
    ]
