# Generated by Django 2.1.1 on 2018-11-13 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20181106_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painter',
            name='image',
            field=models.ImageField(default='user_profile/profile_default.jpg', upload_to='user_profile'),
        ),
    ]
