# Generated by Django 2.1.1 on 2018-11-15 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20181113_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painting',
            name='height',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='painting',
            name='width',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
    ]
