# Generated by Django 2.1.1 on 2018-11-27 15:28

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20181123_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painting',
            name='image',
            field=models.ImageField(upload_to=shop.models.painting_path),
        ),
        migrations.AlterField(
            model_name='paintingimg',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to=shop.models.paintingImg_path),
        ),
    ]
