# Generated by Django 2.1.1 on 2018-12-27 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_auto_20181219_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painting',
            name='material',
            field=models.CharField(default='캔버스에 유화', max_length=250),
        ),
        migrations.AlterField(
            model_name='paintingeng',
            name='material',
            field=models.CharField(default='Oil on canvas', max_length=250),
        ),
        migrations.AlterField(
            model_name='paintingeng',
            name='price',
            field=models.IntegerField(default=100),
        ),
    ]
